name: Caching Workflow

on:
  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: demo-cache

      - name: Create dependency file
        run: |
          mkdir -p ~/.cache/demo
          echo "Dependency installed" > ~/.cache/demo/dependency.txt
          ls -R ~/.cache/demo
