name: Call Resuable Workflow

on:
  workflow_dispatch:

jobs:
  call_workflow:

    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: myapp
      environment: dev
    secrets: inherit

  print_version:
    needs: call_workflow
    runs-on: ubuntu-latest

    steps:

      - name: Print Build version
        run: echo "Build version = ${{ needs.call_workflow.outputs.build_version }}"
