name: Greetings Workflow

on:
  workflow_dispatch:

jobs:
  greetings:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Greeting Action
        uses: ./.github/actions/setup-and-greet
        with:
          name: Shiv
          language: HI
