name: Call Resuable Workflow

on:
  workflow_dispatch:

jobs:
  call_workflow:

    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: myapp
      environment: dev
    secrets: inherit

