name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  test_ci:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run the script
        run: bash scripts/test-script.sh 

