name: External Trigger Workflow

on:
  repository_dispatch:
    types:
      - deploy-request

jobs:
  external_trigger:
    runs-on: ubuntu-latest

    steps:

      - name: Print environmet from the payload fron the external trigger
        run: echo "${{ github.event.client_payload.environment }}"
