name: First GitHub Actions Workflow
on: push
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print greeting
        run: echo "Hello from GitHub Actions"

      - name: Show date and time
        run: date

      - name: Show branch name
        run: echo "Branch name is ${{ github.ref_name }}"

      - name: List repository files
        run: ls -la

      - name: Show Runner OS
        run: echo "Runner OS is $RUNNER_OS"

      - name: break the pipeline
        run: exit 1
