name: Sequential Execution Multiple Jobs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Build the app
        run: echo "Building the app"
  
  test:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Test the app
        run: echo "Running tests"

  deploy:
    needs: test
    runs-on: Deploy the app

    steps:

      - name: Deploy the app
        run: echo "Deploying..."
