name: Reusable Workflow

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
        default: staging
    secrets:
      DOCKERHUB_TOKEN:
        required: true
    outputs:
      build_version:
        description: "Generated Build version"
        value: ${{ jobs.build.outputs.build_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      build_version: ${{ steps.version.outputs.build_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Building App
        run:  echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"

      - name: Check if Secrets exists
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          if [ -n "$DOCKERHUB_TOKEN" ]; then
            echo "Docker Token is set: true"
          else 
            echo "Docker token is missing"
            exit 1
          fi

      - name: Generate build version
        id: version
        run: |
          short_sha=${GITHUB_SHA::7}
          version="v1.0-$short_sha"
          echo "build_version=$version" >> $GITHUB_OUTPUT

