name: Test Accessing Secrets

on:
  workflow_dispatch:

jobs:
  check_secret:
    runs-on: ubuntu-latest

    steps:

      - name: Check if secret exists
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

      - name: Try Printing Secret
        run: echo ${{ secrets.MY_SECRET_MESSAGE }}

      - name: Use secret as env variable
        env:
          USERNAME: ${{ secrets.APP_USERNAME }}
          TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          echo "Application user - $USERNAME"
          echo "Application token - $TOKEN"

