name: Self Hosted Runner
on:
  workflow_dispatch

jobs:
  runner_details:
    runs-on: self-hosted

    steps:
       
      - name: Print hostname of the EC2 Instance
        run: hostname

      - name: Print working directory
        run: pwd

      - name: Create a file and verify it exists on your machine after the run
        run: |
          touch hello.txt
          ls hello.txt
