name: Smart Triggers Workflow

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - 'src/**'
      - 'app/**'

jobs:
  smart_trigger:
    runs-on: ubuntu-latest

    steps:

      - name: Code Change Detected
        run: echo "Code change detected"
