name: Test Workflow

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Test Application
        run: echo "Application is under testing"

      - name: Test Status
        run: echo "Testing completed successfully"
